
package br.gov.cjf.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsConsultaCPF", targetNamespace = "http://webservice.cjf.gov.br/", wsdlLocation = "http://inhambu.cjf.local:7778/wsConsultaCPF/wsConsultaCPFSoapHttpPort?wsdl")
public class WsConsultaCPF_Service
    extends Service
{

    private final static URL WSCONSULTACPF_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTACPF_EXCEPTION;
    private final static QName WSCONSULTACPF_QNAME = new QName("http://webservice.cjf.gov.br/", "wsConsultaCPF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://inhambu.cjf.local:7778/wsConsultaCPF/wsConsultaCPFSoapHttpPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTACPF_WSDL_LOCATION = url;
        WSCONSULTACPF_EXCEPTION = e;
    }

    public WsConsultaCPF_Service() {
        super(__getWsdlLocation(), WSCONSULTACPF_QNAME);
    }

    public WsConsultaCPF_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTACPF_QNAME, features);
    }

    public WsConsultaCPF_Service(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTACPF_QNAME);
    }

    public WsConsultaCPF_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTACPF_QNAME, features);
    }

    public WsConsultaCPF_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsConsultaCPF_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultaCPF
     */
    @WebEndpoint(name = "wsConsultaCPFSoapHttpPort")
    public WsConsultaCPF getWsConsultaCPFSoapHttpPort() {
        return super.getPort(new QName("http://webservice.cjf.gov.br/", "wsConsultaCPFSoapHttpPort"), WsConsultaCPF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultaCPF
     */
    @WebEndpoint(name = "wsConsultaCPFSoapHttpPort")
    public WsConsultaCPF getWsConsultaCPFSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.cjf.gov.br/", "wsConsultaCPFSoapHttpPort"), WsConsultaCPF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTACPF_EXCEPTION!= null) {
            throw WSCONSULTACPF_EXCEPTION;
        }
        return WSCONSULTACPF_WSDL_LOCATION;
    }

}
