INSERT INTO SISOUV.CATEGORIA_MANIFESTACAO VALUES ('LAI');
INSERT INTO SISOUV.CATEGORIA_MANIFESTACAO VALUES ('OUVIDORIA');
INSERT INTO SISOUV.TIPO_RESPOSTA VALUES ('E-mail');
INSERT INTO SISOUV.TIPO_RESPOSTA VALUES ('Carta');
INSERT into SISOUV.TIPO_RELACIONAMENTO (NM_TIPO_RELACIONAMENTO) VALUES ('Servidor do STJ');